using Cache.Data;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo

namespace UnitTests.MockedData;

public static class CodingRegions
{
    public static readonly CodingRegion ENST00000290663 = new(43384450, 43389764, 45, 950, "ENSP00000290663.6",
        "MQREEKQLEASLDALLSQVADLKNSLGSFICKLENEYGRLTWPSVLDSFALLSGQLNTLNKVLKHEKTPLFRNQVIIPLVLSPDRDEDLMRQTEGRVPVFSHEVVPDHLRTKPDPEVEEQEKQLTTDAARIGADAAQKQIQSLNKMCSNLLEKISKEERESESGGLRPNKQTFNPTDTNALVAAVAFGKGLSNWRPSGSSGPGQAGQPGAGTILAGTSGLQQVQMAGAPSQQQPMLSGVQMAQAGQPGKMPSGIKTNIKSASMHPYQRPSCLGFILAIPLRRKVKKLLGQEGKKNAHLQLW*",
        0, 0, 0, null, null);

    public static readonly CodingRegion ENST00000370673 = new(84298558, 84349774, 193, 543, "ENSP00000359707.3",
        "MRGVAEVKEPCSLPMLSVDMENKENGSVGVKNSMENGRPPDPADWAVMDVVNYFRTVGFEEQASAFQEQEIDGKSLLLMTRNDVLTGLQLKLGPALKIYEYHVKPLQTKHLKNNSS*",
        0, 0, 0, null, null);

    public static readonly CodingRegion ENST00000615053 = new(130465653, 130509235, 53, 1579, "ENSP00000483193.1",
        "MVAEVDSMPAASSVKKPFVLRSKMGKWCRHCFPCCRGSGKSNVGTSGDQDDSTMKTLRSKMGKWCCHCFPCCRGSGKSNVGTSGDHDDSAMKTLRSKMGKWCCHCFPCCRGSGKSNVGAWGDYDDSAFVEPRYHVRREDLDKLHRAAWWGKVARKDLIVMLRDTDVNKQDKQKRTALHLASANGNSGVVKLLLDRRCQLNVLDNKKRTALTKAVQCQEDECALMLLEHGTDPNIPDEYGNTTLHYAIYNEDKLMAKALLLYGADIESKNKHGLTPLLLGVHEQKQQVVKFLIKKKANLNALDRYGRTALILAVCCGSASIVSLLLEQNIDVSSQDLSGQTAREYAVSSHHHVICQLLSDYKEKQMLKISSENSNPEQDLKLTSEEESQRFKGSENSQPEKMSQEPEINKDGDRKVEEEMKKHGSTHVGFPENLTNGATAGNGDDGLIPPRKSRTPESQQFPDTENEEYHSDEQNDTQKQFCEEQNTGILHDEILIHEEKQIEVVENEF*",
        0, 0, 0, null, null);

    public static readonly CodingRegion ENST00000347849 = new(130356108, 130373224, 64, 1125, "ENSP00000310092.5",
        "MSRSLDSARSFLERLEARGGREGAVLAGEFSKRCERYWAQEQEPLQTGLFCITLIKEKWLNEDIMLRTLKVTFQKESRSVYQLQYMSWPDRGVPSSPDHMLAMVEEARRLQGSGPEPLCVHCSAGCGRTGVLCTVDYVRQLLLTQMIPPDFSLFDVVLKMRKQRPAAVQTEEQYRFLYHTVAQMFCSTLQNASPHYQNIKENCAPLYDDALFLRTPQALLAIPRPPGGVLRSISVPGSPGHAMADTYAVVQKRGAPAGAGSGTQTGTGTGTGARSAEEAPLYSKVTPRAQRPGAHAEDARGTLPGRVPADQSPAGSGAYEDVAGGAQTGGLGFNLRIGRPKGPRDPPAEWTRV*",
        0, 0, 0, null, null);

    public static readonly CodingRegion NM_001025366_2 = new(43738444, 43752299, 499, 1737, "NP_001020537.2",
        "LTDRQTDTAPSPSYHLLPGRRRTVDAAASRGQGPEPAPGGGVEGVGARGVALKLFVQLLGCSRFGGAVVRAGEAEPSGAARSASSGREEPQPEEGEEEEEKEEERGPQWRLGARKPGSWTGEAAVCADSAPAARAPQALARASGRGGRVARRGAEESGPPHSPSRRGSASRAGPGRASETMNFLLSWVHWSLALLLYLHHAKWSQAAPMAEGGGQNHHEVVKFMDVYQRSYCHPIETLVDIFQEYPDEIEYIFKPSCVPLMRCGGCCNDEGLECVPTEESNITMQIMRIKPHQGQHIGEMSFLQHNKCECRPKKDRARQEKKSVRGKGKGQKRKRKKSRYKSWSVYVGARCCLMPWSLPGPHPCGPCSERRKHLFVQDPQTCKCSCKNTDSRCKARQLELNERTCRCDKPRR*",
        0, 0, 0, null, null);
    
    public static readonly CodingRegion NM_012234_6 = new(72427536, 72495774, 214, 870, "NP_036366.3",
        "MTMGDKKSPTRPKRQAKPAADEGFWDCSVCTFRNSAEAFKCSICDVRKGTSTRKPRINSQLVAQQVAQQYATPPPPKKEKKEKVEKQDKEKPEKDKEISPSVTKKNTNKKTKPKSDILKDPPSEANSIQSANATTKTSETNHTSRPRLKNVDRSTAQQLAVTVGNVTVIITDFKEKTRSSSTSSSTVTSSAGSEQQNQSSSGSESTDKGSSRSSTPKGDMSAVNDESF*",
        0, 30, 0, null, null);
}