using System;
using System.IO;
using Compression.Algorithms;
using Compression.DataStructures;
using Compression.FileHandling;
using ErrorHandling.Exceptions;
using UnitTests.Compression.FileHandling;
using Xunit;

namespace UnitTests.Compression.DataStructures
{
    public sealed class BlockTests
    {
        private static readonly byte[] ExpectedDecompressedBytes;
        private static readonly int NumExpectedUncompressedBytes;
        private static readonly Zstandard Zstd = new Zstandard(1);

        static BlockTests()
        {
            const string polyPhenBase64 = "G4D6gHGAUIA0gDSA+oAagDKACoD//3GAUIBQgE2ANIAygBqAbYFxgAOASoAAgP//NIACgCSAGoACgAyASoACgBCAB4AMgAKABYAJgJWANIAEQ8gDiAOsA8oD///KA8oDvAO8A8oDjAO8A7wDugNOQ6wDugPKA8oDp4FpQ+2A//86Q6eBOkOqQkaBKkJpQ7KBKkJBQrKBsoGygSBCaUMGQwCAAIAHgASACIAEgBmAAoACgAKAGYAEgBSAB4D//wKAAYABgCSAC4ABgCSAB4ADgAKABYAZgAGAAYAAgAOAB4AUgAeA//8DgAKAAYAkgAiA//9mQ/BCdEJmQ/5BiwN+Qn5CCUJmQ/BC6ELwQvBC/kH+Qf5BiwNmQ3mAA0NhgWGBW0K7gAND1UFhgWWBA0NhgVeB1UHVQf//tYBhgYFDW0IBgDqAA4ABgBSAA4AMgA2AAIACgB6AAoAHgP//AIACgAOAA4A6gA2A//9KgAWADIA0gACASoAQgAWAB4BKgAmAEIAagBCAAoAHgAqASoA0gACAAIAAgACAAIAAgACAAIAAgACAAIAAgP//AIAAgACAAIAAgACAAIB5gPtCYYFhgVFCu4ADQ9VBYYFhgQNDYYFXgdVB1UH//7WAYYE/Q1FCAYAZgASAA4ACgAGAGYADgAOAAYAZgAeAC4AEgAiA//8DgAOAAIABgAuA4YAAgAiArID//6qAe4AXgESA6IAOgFyAXIBZgA2AIIBZgJCB6IAJQosDZkPwQnRC8EKIA4iBfkL///BCZkM3Q2ZD6EJ+Qn5CiIGLA/BCckKsA+NC40KsA+NCrAOTA+NCQUOsA3ZD//+lA6UD20LbQuNCrAOTA///SoACgACANIADgBqAEIACgAOASoAEgAuABIAEgAKAA4AEgEqANIAEQ8oDjAOqA8oD///KA8oDvAO8A8oDjAO8A7wDvQNTQ6wDugPXA8oDBEPIA4gDrAPKA///ygPKA7wDvAPKA4wDvAO8A7oDTkOsA7oDygPKA///dYAAgASAVIAEgDqAG4AGgAyAdYAGgByAFIAUgAeABYAJgOKAVIAAgACAAIAAgACAAIAAgACAAIAAgACA//8AgACAAIAAgACAAIABgACAAICqgCyAH4B7gP//6IAygBeAF4CqgCyARIBcgEaACIAOgA2AXoF7gAOASoAAgP//NIACgCSAGoACgAyASoACgBCAB4AMgAKABYAJgJWANIB+gPtCYYFhgVtCtYADQ8tBYYFhgQNDV4FhgdVBy0H//7WAYYE/Q1tCAIAzgAeABYAkgAKASoAGgASAAoAzgAyA//8VgBWAAoACgAKASoAkgARDygOMA6oDygP//8oDygO8A7wDygOMA7wDvAO6A1NDrAO6A8gDygMCgCOAAIACgA6A//8lgAGAA4ABgBuAA4AMgA6ADYACgAOAAIA1gBqAAYBXgACAAoAkgP//M4AagASABoBKgASADIAMgBiAAIAEgAiASoAkgP//JYADgAWACoAAgDWAAYAEgAGAE4AGgBWAE4AMgAOAAoAAgDWAGoByQqwD40LjQqwD40KqA5MD40I4Q6wDdkP//3ZDckPbQttC40KsA5MDAIAAgACAAID//wCAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYAAgHJCrAPjQuNCrAPjQqwDkwPjQkFDrAN2Q///pQOlA9tC20LjQqwDkwMAgKSAKoAggHuA///ogDKAF4AXgKqALIBEgFyAQoAIgA6ADYDogHuAAYBTgAWABYAtgACAPYATgAWACIA9gASAC4ATgBOA//8FgAuAVoA9gACAGIADgAOAAoADgBmAAIADgACABoAEgAeAC4AHgP//AYAAgCSACIABgACAA4AGgCSA//8zgAaABIAEgEqABIAMgBOADYAAgAKAA4BKgCSAeYD7QmGBYYFRQruAA0PVQWGBYYEDQ2GBV4HVQdVB//+1gGGBP0NRQgGAOIADgAKAJ4ACgCiACYACgAKAKIAFgACAB4AHgP//A4ADgHeAJ4D//0eABYAFgDKAA4BHgBGABYADgGWABYAegBGADIAAgAOAA4BlgDKACUKLA2ZD8EJ+QvBCiwOSgX5C///oQmZDN0NiQ+hCfkJ+QoiBiwPwQglCiwNmQ/BCfkLwQosDkoF+Qv//6EJmQzdDYkPoQn5CfkKIgYsD8EIBgDqAA4ABgB6AAoAcgAWAAYACgCiABYAAgP//BIACgAOAA4B3gBOA//9mQ/BC90JmQ5NCiwN+Qn5CCUJmQ/BC6ELwQvBC/kH+QQ5CiwNmQwWAdYAAgP//VIAEgDqAK4AEgBSAdYAEgBuAC4AUgASACIAPgOKAVIC1gANDW0LLQdVBV4E/Q36A1UF5gFFCW0JbQltCxULVQWGB//8/Q1tCCUKLA2ZD8EJ+QvBCiwOSgX5C///oQmZDN0NiQ+hCfkJ+QoiBiwPwQnJCrAP///1BkwNyQpADkwPjQj5DrANyQj5DPkN2Q3xC40I4Q6wDkAMJQosDZkPwQn5C8EKLA5KBfkL//+hCZkM3Q2JD6EJ+Qn5CiIGLA/BCckKsA///kkKTA3JCkAOTA+NCPkOsA3JCPkM+Q3ZDfELjQjhDrAOQA6eBaUPtgP//OkOngTpDqkJGgSpCaUOygSpCQUKygbKBsoEgQmlDBkNyQqwD//+SQpMDckKQA5MD40I+Q6wDckI+Qz5DdkN8QuNCOEOsA5ADp4FpQ+2A//86Q6eBOkOqQkaBKkJpQ7KBKkJBQrKBsoGygSBCaUMGQ3JCrAP//5JCkwNyQpADkwPjQj5DrANyQj5DPkN2Q3xC40I4Q6wDkANyQqwD///9QZMDckK3A5MD40I+Q6wDgUI+Qz5DdkN8QuNCOEOsA7cDCUKLA2ZD8EJ+QvBCiwOSgX5C///oQmZDN0NiQ+hCfkJ+QoiBiwPwQqeBaUPtgP//OkOngTpDqkI4gSpCaUOygSpCp4GygbKBsoEgQmlDBkO1gANDW0LLQdVBV4E/Q36A1UF5gFFCW0JbQltCxULVQWGB//8/Q1tCcoFhQzVD9EL//0dCs0LsQfRCmIBmQzVDZkM1Q/RCPEKzQmiBMkMPgI2AH0NPgU+B5ELmgCZD60ELgQuBJkNGgQaAoUI7Qv//EYDSgIVD5ELEgBdDJ4FdgBdDbYHPQn5C//8ngRBDY4EwQhCAjoDEgGOBu0F9Q9JCMIGNA///ooGNAw2AiQNpQ1pCN0ONAz+AaUNpQzdD1EGlQmRDvQOJA///U0M5Qs9BHENEgVND9kHPQc6AU0OQQoZC1UKQQoWADYDHgJ4DU0MOgF1Dr4FigSpDlYBdQ+VBYoEVgV1DNkIrQqRCpEL//xmA3YCkAypDbEK1A58DnwN8Q58D0ANzgJ8D//98Q7UDtQO1A58DgkMbQ0yBzwOfAwKA50FGgEaAx4AXgOdBMoAygA+A//80gAGAXoBDgAOAAoAPgPFCLIHdQsMD//8hgMMDFkOwA8MDn0KBQ8MDFkObA/1CYEPmQl9DmAPiA8EDAYArgSyAIYARgACAK4EAgB+AAYD//yGARoBGgEOAC4AQgACAf4FGgBxC0QMLQxJDxgNvQsUDxQMLQ4JD0QP//8YDpQOCQ5WAhkKlA90DxQOtQt0DoAOCQ9ADREPRA8YDgkOCQ9EDoANRgMYDxgP//z5DugPdA9ADUoF0Q01DE0P//9dCeEMBgRNDCoBDQk1DeEN4QxNDz0KSQgGBeEPhQeVCzQN7QgNDwwNQQsMDwgMDQ5oDzgNQgLYDoAN1Q///mUKaA9wDwwOKgM4DtgN5Q84De0LNA7MDeUNPQ84DwwP//8MDsANxQk9DKUPkA84DA4C9gA2ADYAPgAmAvYADgA2AAID//w2AKIAogBGAAYAAgASA/YAogEGAykIpQrRBpIBXgcpCA4DhgAKA//8pQilCKUK9QemAhYADgMpCyEHZQsoDdkPKQpcDZkPKA09DykJZgKwDqQP//1CBckM3Q2FDykLKA8oDJ4CXAytCd0IXQ1SBlwM5gG1CnoBPQy+AEENIQxBD6YD//56AwQN2Q11D+0HOA84D3wO8A+QD1gPOA7QD4APOA9sD3APcA///ugPQA+cD3wPmA+gD5wPnA+cD5wPnA+cD5wPnA+cD5wP//+cD5wPnA+cD5wPoA+cDIoB4Q9RBUoEXQ7eAeEPiQVKB//9NQ9RB2ELYQpNCEYC3gOiAsgNNQ4BD5APOA84D4AO8A+AD3APCA9cD5APOA4WB3APcA///ugPcA+cD4AOaQs4DwgN1Q7QDdUPOAytDcUOQQv//sQPCA7QDsgO+QsaAkELcA8IDUYG0A54DfkNbQ1tDtAP//3pD4IB6Q54DngO0A5sDW0OSQhWA0AOeA+cD5wPmA+YD5wPlA+cD5wPmA+cD5wP//+cD5wPnA+QD5gPnA+gD5wPhA+cD5APcA+cD5APnA+YD4QPkA+cD5QPmA///5APkA+UD5QPnA+YDGYB8gaCAY4AOgEqAtYD//0qABoDigJqA6YA2gemAR4AYgAGAKIEBgG5D4APHA0FD1wO0A9cD0AP//50D1wOaA9ADmgN3gJ0DsgPQA+AD1wNuQ9cD0APQA///xwPgA9FC0AN3gMUD0APXA9cD0APGA7QD0ULgA48DwAPnAy+B///gA8AD4APgA8AD3APkA8cD3APXA9wDwgPXA9sD5wPkA7ED5AP//9aA4APAA98D4AOHQ9YD4APAA9wDuwPQA7QD0APWA+cD3wO6QbQDKID//7QDJYC0A54DXUJ+Q7QD3UKeA0xDW0PFQRhDVkPQA7QDJIBjQgWAA4AHQj2AY0K2QWCAlYC7QmCA///FgMWAA4BcgMyAu0IHQhBCtAP//wyAtANdQpoDngPFQS9DtAPVQltDS0L7QhpC3UJWQ9ADsgNZgL0DyEJ9Qm5D+UG9AwaB+UH//4KBfUJzQ01DTUNLgFmAMYDUA6sDlgPgA8QDTkPgA8QD3APXA///tgPgA7QD3QOlQo+AlgPCA9ED5APdA+gD6AP//+cD6APnA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6AO9A+QD5APiA9wD4gPkA3CB4gP//+AD5APkA+QD5APiA9gDIkPmA+IDxgPkA+ID4gP//98D5gOPA+ID8EHfA+ID5APkA+ID3wPfA48D5gPQAyxC0gPIA6kDY0OpA9ID//+pAyJCuAPHA8gDyAPIA4RDOkMygN4DC0K6A+YD4gPiA+YD2gPmA+UD4QPeA+YD4gPlA+UD4wN3Q///3gPnA+YD5wPoA+gD6APoA+gD6APnA+gD5wPoA+gD6APoA+gD6APnA///6APoA+gD6AP//+cD6APnA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6AMTgIwDCoD//2dDGoFLgNFCZIGPgagDNYDyQo6AM0IjgY+BhYHKAz5D5wPoA+gD6APoA+gD6APoA+gD6APoA+gD///oA+gD6APoA+gD6APoA+cD6APnA///6APoA+gD6APnA+gD6APoA+gD5wPoA+cD6APoA+gD6APlA+gD5wPnA+gD5gPoA+gD5wPnA+gD5wPoA+gD6AP//+YD6APoA+gDYEPaA6cD/kJKQ6oD///AA1FDTEPaA6cD0wMVQnRDlAPAA58D1AODgDBD2gPTA9QDsAPTA9oDVoDLAxVCwAPaA9QD2gPaA8sDlAP//+YD1AO8A+QDygPYA+QDuAPiA+ID0gPWA+QDQELiA+AD3AOWA///1gPnA+QDHYDSA4gDZ0O6AyxC0gNjQzpDLELSA4gDhEO6A6cDIkL//yxC3gPIA75BmwN7Q3tDLENYQ7ID//9SQ9uAUkOcA3tDsgOYAytDOkIXgLIDe0PnA+gD5wP//+gD6APoA+gD5wPoA+gD6APoA+cD6APnA+gD6APoA+gD5wPoA+gD6APoA+gD6APoA+gD5wPoA+gD6APoA+gD5wP//+cD6APoA94D5gPlA+UD///lA+QD4QPjA8cD5gPmA+YD5gPmA+MD5QPaA+YDzEL+QtoD1APLA78DywPaA///ywOTQsoD0wPUA9oD2gO/A3RDjYDiA9QDc0PhA9oD0gPUA9ID4QNlQ9wDAYEmQ9oD3gPeA+IDwgP///lB5QPeA+gD6APoA+gD5wPoA+gD6APoA+cD6APoA+gD6APoA+gD6APoA+gD///nA+gD6APnA+gD5wPoA+gD5gPnA+gD5wPoA+cD///nA+cD6APoA+gDLELSA8gDqQOQA4gD0gP//6kDMYGnA8cDyAPIA7oDY0PdQh2A3gO6AwqAjQMzQjNCqEIjgagD///kQVmAjoBfQoBC8kKxQhqBIIAKgMoD8kLnA+gD6APoA+gD6APoA+gD6APnA+gD6APoA+gD6APnA///5wPoA+gD/kLaA58D9kLaA5QD1APUA///eEPTA5wDywN+gRWBUUOwA8AD4wPaA4ND4QPeA94D1QPaA+EDLELZAxxD2gPeA94D4QPeA8cD//8cQ+UD4QOnQtsDakNqQ9UDKkPbA4FDakMOQ9sDakOsA8MDrwP//1SADkPiA9UD5wPoA+gD5wPoA+gD6APoA+YD6APoA+cD6APnA///6APnA+gD6APoAwVD4AO2A7QD4AP//+AD1wOlA8gD4AOlA9cD1wPQA92AjAPQA+QD4AN2Q+AD4ID//+ADtAPcA9cDTkPIA+ADtgPYA8tBjAN6Q7YD0APkA90D5wPoA+gD6AP//+gD6APnA+gD5gPoA+gD6APoA+gD6APoA+cD6APnA+gD6AP//+cD6APnA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6ANWgH6BqgOUA8oD/kLaA7IDeEP+QtoDqgPKA8sDywP//zBDUUPiA9MDnEKDgL0DzQPaA31D2gO/A70DUUPaA8wD1APUA9MD//9aQ58D4gPaA+cD6APnA///6APoA+gD6APnA+gD6APoA+gD5wPoA+cD6APoA+gD6AMdQ9EDyAOpA///iAOUA2NDqQMiQtIDyAPIA8gDugOEQ4gD3UK6Ax2A3gPoA9YD///mA+ED5gPmA8cD4wPmA+MD5QOfA98D3gPiA+UD6APmA+cD6APoA+gD6APoA+gD5wPoA+cD6APoA+gD6APoA+gD5wP//+gD6APGA+YD3wPGA+ID2gP6QeIDsAPaA+QD1APiA9QD///TA9oD4gPmA9sD5wPoA+gD5wPoA+cD6APoA+YD5wPoA+cD6APnA///5wPnA+gD6APoA+cD6APoA+cD6APoA+gD6APmA+gD6APnA+gD5wP//+cD5wPoA+gD6APoA+gD6APoA+cD6APoA+gD6APnA+gD6APoA+gD6APoA+gD6APoA///5gPoA+cD5QPoA+cD6APoA+YD5wPoA+cD6AP//+cD5wPnA+cD6APoA+gD6AP//+cD6APnA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APnA+gD6APoA///6APoA+cD6APmA+gD6APoA+gD6APoA+gD5wPoA+cDvQPkA+QD4gPcA+ID5ANAQuID///cA+QD5APkA+QD4APYA3hC5gPkA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APoA///5wPnA+gD6APoA+gD6APoA+cD6AP//+gD6APoA+gD6APoA+gD5wPoA+gDxgPmA98DuAPkA9oD5APiA///1APkA9MD4gPTA1yB1APaA+ID5gPkA+SAlQNNgReAlQP//0tDREPPQSRClQMkQhNDQ0KGQhiATYHPQpUDlQOWA+AD0QN2Q+ADxAPgA9wD//+2A+ADtAPdA7QDj4C2A8ID0QPkA+AD5wPoA+gD6APoA+gD6APnA+gD///oA+gD6APoA+gD6APoA+cD6APoA+cD6APnA///6APoA+gD6APnA+gD6APoA+gD5wPoA+cD6APoA+gD6AMJQrIDF4D//7IDOkKbA3tDs0FYQ7IDRUJ7Q89CWEO+QZVCd0PfA7ID///kA8MDwQPkA7gD5APiA8JC1APkA8JC4gPbA7QD10KnA9MD5gPkAyND4QPHA7MDlwOgA///2QPIA7sD4QOwA94D2gPHA3lCrQPIA+ED7kHnA+gD6APoA+gD6APoA+gD6APoA+gD6AP//+gD6APoA+gD6APoA+gD5wPoA+gD6APoA+gD6APoA+gD5wPoA+gD6APoA+gD5wP//+cD6APoA+cD6APoA+gD6APoA+gD5wPoA///6APoA+gD6APoA+gD6APnA+gD6APmA+gD6APoA+gD6APoA///6APlA+gD6APoA+gD6APoA+cD5QPoA+gDVEPhA94D2gPTA9oD4QP//9oDxELZA94D3gPeA94DxwOdA+6A5QPeA5sD5AOEQ4RD0wOEQ8SA2gOeA7oD3gOigf//ywOpA4FDmwPKA+QDwQPFA+YDXIH//+QD0wPkA+IDxQPiA+YDzQPiA9oD4gO6A9QD4gPnA+QDHkPNA80DwAOXgJsDvwNhQq8D//+yA80DzAPNA78DmwOvA2FCwANdQ2GAwQP2QhtCRUP4QcIDmIBuQjaAmwO1QkVD6YAbQ///N4CjgdcDnAOcA+YD2gPUA+QDxgPkA+ID1APUA+QD2gPrgOID4gP//8UD2gPmA+QDHUPSA6IDiAOiQogD//+UA2dDA0PSA4RDxwOnA4RDZ0OpA0BDyAM4gN4D5wPlA9oD5gPkA+YD5gP//+ID5gPjA+UD4wPMQt4D5APlA+gD5gPnA+gD6APnA+gD6APoA+gD///oA+gD6APoA+gD5wPnA+gD6APoA+gD5gPoA+cD5QPoA+cD6APoA+YD5wPoA+cD6AP//+cD5wPnA+cD6APoA70D5QPjA+ED4QP//+UDyAPhA8gD4QPjA+UD5QPjA94D1QNVQucD4wM3Q+YD5QPjA+YD2gPmA+UD4wPhA+YD5gP//+YD5gPcA+ED4gPoA+YD5wPoA+gD6APoA///6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APoA8YD5APiA+IDXIHiA+QDqgPiA///4gPkA+QD5APiA98D3wO4A+QDtAOrA+AD4APdA9mA3QPgA05D3QP//90D4APgA+AD3APdA9gDdkPgA60DI0PhA70DvQPeA4ND4QPAA60DlwPhA6sD2QPZA9MD//9agbQD5wPhA/5C2gPUA6oDwgOnA9oDngNaQwBCFULAA9QDsgP//5EDkQOEQ9oD1APNgF1D80KSQvhBkkKGQ3+AtUETgP//X0M0QzRD60K/QR6BBoC5A/NC5wPoA+gD6APoA///6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APoA1BD5APmQmuA2gOeA9kD2gPeQpsD3gOeA8gD//+BQ1BDngO8A+QD2gPfQcADMUMxQ8AD4ULAA5gDMUPhQs0DK0OYA5sDgUNjgP//4ULNA8ADvAPkA+QD4gPhA+ID5APyQeIDc0PiA+QD5APkA+QD4gPPA///5wPkA3pD4APIA1RD4AO0A+AD1wPggLYD4AO2A9cDpQP//6IDtAPRA+QD3QP//94DrgOdA9kDK0PeA8sDsQOUA94DsQPSA8sDywNYgXFDkAPmA94D0kLYA8QDuAOMA7YD2ANoQqgDU4HxQdAD0APHA8cDuANkQ///2APFA///6APoA+gD6APoA+gD6APoA+cD6APoA+gD6APoA+cD6APoA+gD6AMPgAdDu4AwgdSABYAjgFiA8IAFgICBD4AEQq2BrYH//52AW4ACgNSA5QPoA+cD5wPoA+YD6APoA+cD5wPoA+cD6APoA+gD///mA+gD6APoAyiAwEKBgc6AAoDOgMBCDoDIgAGA//+BgYGBgYEggZ6AdIABgAhDWYDnA+gD6APnA+gD5wPoA+gD5gPnA+gD5wPoA+cD///nA+cD6APoA+gD5wPoA+gD6APoA///6APoA+gD6APoA+gD6APoA+gD6APoA+gD6APoAyND2wPVA88DwgPOA9sD3oDDA5iAzQPWAzCB1gPWA68DakP//+ID1gM2Q9oDwAMwQ9oDlAPUA8oD//94Q9oDkQPUA3RDVoB4Q5EDywPiA9oDcoBIQ6yABYEOQxKAB0PKQv2AeoF2Q///jUIcQs1BBYCsgHqBdkMHQ+cD6APoA+cD6APoA+gD6APmA+gD6APnA+gD5wP//+gD5wPoA+gD6APnA+gD6APoA+gD6APoA+gD6APoA+gD6AP//+gD6APoA+gD6APoA+gDWkPaA1aA///aA3RD2gPLAzBDywPaA1FDywORA8sD/kKUA8oD5gPaA71BtAMlgP//MkNDQp0Dy0G9QUqB6YBOQlxD10IxQ8dBnkI/gLQDngPnA+gD6APoA///6APoA+cD6APmA+gD6APoA+gD6APoA+gD5wPoA+cDBIAoQ4CAq4D7gFuAMkIKgHuAIoD//waAhIE6gfOAE4AEgCKAtQNcQiKBqgMUgP//bEPjQY8DmIGOgT6AbEMfQvlCXIAfQpiBPEJcgKoDkANqQ9sD1gPPA6UDzwPbA6dCvwNegP//1gPWA9YD1QPBA6wDp0LbA9YDI4GoA2SBI4EMQxSAfYAygDqAw4BnQ///8kI8gI+BIIAagcOAygPqQiOBqAMKgAqAZ0MjgWND6kIageRBjQP//4BCI4E8gCCAGoEzQsoDakMlQrwDlgM4Q///3EIfQ45COEN4gasDc0OrA6sDc0P9QjhDy0GQAw+AI4GoAzND8kLZQYBCqAP//zNCCoBZgDhDM0M+QwxDKEJkgRGAqAPyQpVC0gMdgP//0gNWgNIDyAMWQ6kD0gMKQ70DhEOpA59CiAOnA94D0gMDgExCA4AJgFaAN4BMQgGATID//wiATIDDgJWAlYAjgAOACICjQi+B5wPoA+gD6AP//+gD6APnA+gD5gPoA+gD6APoA+gD6APoA+cD6APnA8ID5wPhA+ED5gPzQeYD5QPhA+QD5wPhA+UD5QPlA///3APlA+gD5wMqgaoD7UEigURDw0EUgGCAbYEigZADYIAyQ///40FlgO1BmIGqAx9ClwPhA5cDNYHhA8wD3gPdA///zAPhA8sD2QOyA6sDlwPLA9QD5wPhA7oD5APiA+ID3wPiA+QD///eA19DX0PkA+QD5APiA98D0wNfQ+YD4gOwQiKBZUNqQ9YDsELbA8wDPUObA9sD///NA80DtgP4gAZDmwPiA9UDgoFogAVDBUNHQ05CvQNOgAVD//9uQwVDlgOQA5ADVoCCgTGA0wOrAyVCvQOrA2pDyEJqQ70D//8yQw+AEIGrA6sDqwONAzhD00IugL0DlgPoA+gD///nA+gD5wPoA+gD6APoA+gD6APoA+gD6APoA+gD6APoA+gD5wPoA+gD5wPoA+gD6APoA///6APoA+gD6APoA+cD5wPoA+gD6APoA6oD5APiA+ID3wPiA+QD///iA19D3gPiA+ID5APkA9sDywPwQeYD4gNdgNEDiAMdQ8cDLELSA5QDZ0OfQtIDiAOnA7oDqQP//1iAn0LeA8cDd0LJA99Cy0GoA99CKICoA8tB10LJA05CqQP//6+A30JlQ2VD2gPIQucD6APoA+cD6APnA+gD6APmA+cD6APnA+gD5wP//+cD5wPoA+gD6AOZA+QD4gPiA98D4gPkA///4ANpQ+ID5APkA+QD5APfA84DcIHnA+IDZYDBA+5CtULuQkZCM4BlgLVCo4GbA9tCeEMbQxtDmoD4QWWA1wP//8YD5gPfA7gD5APUA+QD4gP//80D5APTA+IDywNcgdQD0wPiA+YD5APnA+gD5wP//+gD6APoA+gD5wPoA+gD6APoA+cD6APnA+gD6APoA+gDRIGVA+SA//+VAxpCS0MTQ+SAz0FxQ89B10IOgM9BTYEkQhpClQNEQ/5C2gOyA/5C2gN0Q9oDywNWgJQD2gOUA8sDUUP//0xDkQOyA+ED1AOoQtQDPID//9QDXYDUA74D7kK+A9QDGEO+A2xDmgOxQnFDrAPfA9QD2gPmA+YD5QPQA+UD5QPOA+UD1ELkA+UD5gPlA+UD5QPjA84D5wP//ziAu0LbgNuA//+MgCJCNoCMgAKAgIHbgNFB0UGEgQeAW4APgMRCCIAigaoD//8KgNVCIoE+QxJDmIEfQqoDH4D5Qh9CH0JggJiBsEKPA0uAlgPnA8gD///kA12B5APkA9UD4APkA9wD4gPgA+IDzwPcA+ID5wPkAw6AMEOcQrlBJoEEgWJDlICvgQSA//+cQpxCnEKSQsyAPoFhgGJDnEKpgDFDSoEdgO9Ck4HvQplC//8DgTFDQYGiQvuABoCpgEGBCEIxQ+9CxoDOAytD///OA/RCzgOxA/FBUEPOA3VDtAMJgRKBvkJ1Q0pD3APCA2SBHYCGQ2pDHYDqQoZDhYFqQxqBpQOGQ4oDigOKA+JC6kJZgKUD//8cgdcDtgM2Q9cD///XA8UDY0OnA9cDpwPQA3BCtgNvgWNDpAPgA9cD5gPoA+cD5wPnA+cD5wPnA+cD5wPnA+cD///nA+cD5wPnA+cD6APnAxmAfIFKgEqAWIBKgAmA//83gAmAD4BHgKCAoIB5gAaAAoABgNtBoIBUgLtCPoGqgCWAqoD//5qAqoBcgGNC1YANQj6B/ICqgASBYIAUQgKAAYAhgS2ALYBVgBiAeIH//xiABoCpgCCAYIBIgAKABoABgAGAk0KbgKSBlwNIQ9ZBSkJ3QpcDVIHWQf//QkNIQ3FD6YA5gL9Cd0JGgDeAlkLHA98D4APcA8cD1wPgA7oD3AOFgdcD4APgA+AD3wPbA9YDqQP//9cDhoDOA3JC/ELCAxmAwQOxA/xCSkPOA3uAsgOxA4ND///0QlBD3APCA///UkPNgA6A1EIOgBlDn4HNgM2AUkMfgIVCN4AzgYSAFIDQgJ4DG0MygDlCUoBwgIyBNIA5QoWAUoAEgDlCBYA5gUKBsoD//wSAUoCWQtxBaUPXA48D///FA7ID4ANxQ48DJYHQA8cD0AOyA8cDtAO0A15D4APXAxyB1wNBQ///1wOAQ9cDxQPRQoRD1wO4A8cDb4FjQxdDnQOAQ+AD0ANKgZcD//8IgJcD6EFwQ0hDVIF3QpcDmoEXQ3aA1kFUgXdCbULBA3FDIkPNA80DzQOdA8IDzQOpgLED//+aA80DzAPMA8wDsQOdA+ZB5APNAwGAOULdgLKA0UFPgJZCMoCFgDKA3EFCgeWAjIFCgTSACYD//5ZC3EHpgJcD//8IgHZD6EFwQ0hDVIF3QpcD6EEXQ9ZBmkJ2gKSBtkLBA3FDA4DKQkGAQYB5gUGAd0IGgEGAKIDIQWKAAoASgRKBA4D//yiATkMpQqgD4APgA9wD1gPcA+ADR0PcA///AkPgA98D3wPbA9wD0ANwQ+QD3ANUgZcDK0I4QpcDD4CXA3ZD//+/QpMDRoB2Q7ZCRoCkgbZCF0PBA3ZDBIAGgf//DoBKgACAkIAJgA+ACYDEgAGALIAsgCGAAIAPgAGAWIFfgG+ANkOhQmBCZoFWQjZDCoARQgaAFICqQvlCYUJhQp2BU4H//zZDqkL//+QD2wPCA9wDugOYQtwD0APOA+AD1gPbA9YD1gOlA80DzQPkA9YDYYASQwiAlIDUQgWA0UJ2QpSAb4EZQwWAj0LiQWWB//8ZgG+BfkPUQuED///mA+cD5wPmA+cD5gPmA+QD5wPnA+cD5wPnA+UD5QPkA+cD5wMmgORBhYDigF+AbYBGQv//roABgLyACYCIgehBPoFpgDmAAYBGQj6BukG0A///F4CdA9VCmgO3QktCS0K0A5JCfkO3QvdCxUHdQpeA3wOyAxmA20EogBmAf4EYgOmAroABgCiAKIEBgHmAAYD//xiAJoB5gNtBKIGwgP//6UHpQQRDbYF0QwKBd4EggAxDOkIMQ89Cx0IbgAKBSYGuA0JDVYH//xpD4EJFQmFCn4AaQ+BCHkK1A+BCnwN/Q1hDboAeQmtCsgM/gLeAeEPUQTOAE0MjQktDgIH//zWADEPKQdhCKYAQgAqBkoE1gHhDTUP//6UDe4EggEiAbEKlAxKBhYEagYgDOENlQ8hCBUMeQh5CMYClA8hCvUHgA9wD0APgA6ID4APWA9YDtAPgA9sD2wPcA9wDcEP//7QD5APgA9lCygMogP//qQM3Q8oDIEPZQvaAvAPKQrwDYUOTA6BCZkMEQ9oDygOJgFJDzYANgBtDTYHUQvRB///NgExDQ4EVgAKBB4CJgBSAzYCeAxtDiYBSQ4GBiYBFQtZBFYAzgYmAFoCPQguBBEMOgP//zYBNgTOBVENDQjKAUkJZgJ6AWYA5gPJBAYBLgAGA//8FgI6BNYGZgDmAZIAFgKlCNYEBgASAaIA5gAOAOYDyQSKACYADgFWBToDHgAmAOYD//wKAA4CpQgmACIATQwiAWoA8gf//DoDYQQ6Av4ATQ5CAtEEkgBiAXoD1gIuAE0MkgN+AMUPyQqJCDoBXQudCo4CiQv//V0IxQypDMUOZQldC40EdgO9CtEEKgHhDCoGcgU1Dt4B1gJNCnIECgXhDHYDPQthCcUL//zOAgIGyAxND0EG4AyiA//+kAyiA94CkAyZCJkO4A69CjAP4gO5CfEImQ1dD0gOGQ///dIEXgAKAA4AXgAKADoAYgA6A44ABgF2ABoA1gASAAYABgNNBWICoA+QD1gOHQ9wD1gPgA7wDuwP//9sD1gPbA/pCzwPQA8IDugPkA9wD2oCNA1lCWUIegAxCiQMjgFlC//82Q8NCY0M2QzBDQYBBgCiAjQMrQuYD6APnA+cD5wPnA+cD5wPnA+cD5wPnA///5wPnA+cD5wPnA+gD5wMDgNpCcIF6geJBBYAgQwmAM4E8gD1C7UE9QopCPUKagM2A//+CQ91CLIGXA3ZDcUOaQktDlwMZgBdDCIDeQnZDdkN2Q0hDv0LzQf//lwN2QzBCuAPmQttBYUJ8Qv//hkPbQeZCuANyQqEDdoBWQjBC7kImQ7gDdoBpQ+ADs0L//9cDgEPXA9ADaUPHA9cDJYHQA7IDuANHQ50DzwPlA9cDnQPXA88D0ANpQ9AD3AM2Q9ADJYHQA88D1wPQA9ADxgPHAxdD4AP//3BCygO8A7sDl4CqA8oD2EG8A0iAlAO8A7wDygO8A60DZkP//8oDUkOoA+AD4APcA9YD3APkAxxC3AP//9wD4APfA+AD3wPcA9cD+kLkA9wDVYEYgBNDGkP5QhmAnAMaQxpDpoG1AxNDhUOFQ4VDdIBrQmtC0AP//zeAwQNxQvdCswPwQcMDFkO3QnFCwwOUgHlDeUNHQ///YoBxQtcDswNpQ9cDsYD//8UDmgPXA3FDaUMlgdADhEPQA7IDxwNuQ7QDXkPgA9cDBoAJgRyAHIABgByACYEAgBOAAYD//xyAPIA8gCqACYAAgAGACYEUgCWB1wPQA8UDwwOnA9cDHIHFA///0APQA9AD0APQA15DnQMcgeAD0AMFgFJCnoBOgPWAOYBSQiGABYAOgP//eYDOgJ6ANoAJgDaAAYA5QzWBAYAvQgSADoDcQf//6UH9gIWAhYA5QgSAQoFCgfmAMoBSgICAlkLcQfiAnQOkQupBekM1QnxDTUIagD6BnQOtQlNDqUJeQn+AuUH//8QDfkOngBNDh0IVQgWAFUITQw+ALYECgP//h0KHQodCqYE2gS2BOoATQ+CAGkK0A1tDEEK0A91CnQN6Q///m0K0A9VCngOSQheAm0LVQltD0AO0A7CAS0PCQcWA40G3QUtDiYEMgAyA40HCQYRCPID///mAt0EpgUtDykK5QZ0DfkPQQvRCHkOdA59CTUIagPRCfkN+Q35D//8eQ4FCXkKdA3xD5gPnA///4wPnA+UD5wPnA+cD5wPnA+UD5wPnA+cD5QPnA+cD6APnAyeAT0IngDSABYA2gAOAPoA0gCWA8kECgAKA//9SgDaAC4AGgE9CPoBIgIxClIFJgQKBAoHfQv//+oAEgDyBRYHiQeJBioGzgAaADIDfQjNCg4BLQ4OAB4ATQ0KBMoDKQn+AOYFLQwGBCEL//76APIABgcJBmgOEQv//nQPqQeBBU0MZgJ0DqULqQepBnQNeQk1DJUMlQxuAK4DgQcQDnQO+gEtDBID//+NBC4ARQ8pC+YDCQUtDKYGEQrdBN0LFgMJBCEJLQzSArIAZQwiAlIAFgMWAMkKUgBqA//92QueAdkLXQd+AlID8gF2A0UIJgLCAeEP//wWAE0MCgUZDE0MKgdRBeEMCgXFCVoDUQR2ACoEYQrIDSEMDgMFCA4BBgJ6AQYDIQWaAioAogBmAZoBOgRKBEoH//3OAC4B0QgmAsIB0QwKBMYBGQwKBFUPHQv//ykFGQ22Bz0IngBCAHID6gMpBdENIQwWAGUO/gPyAioGPgBlDBYDFgDmAMkIRgL1BMkJvgWGACYD//35DgELpgJcDD4D//5cDmoGXA0hDF4ArQpcD1kEXQ8tB1kF2gCtCbULBA5cDAIDEgA6AAIBfgAmAxIAOgA+ACYCWgBSAHIAXgBeAAoAJgP//WIFjgLCAdEPPQopCgkJ3gXRDqoDKQf//bICMQgxDz0LPQjGAAoEbgHBDDEMBgNtBKIA3gEKAAYDpgAKAKIABgAWAAoCagHmAW4AYgP//D4B8gQOABIC9gA6AD4ABgA+AbYAPgA+AAYCWgACALIAsgCGAAIABgA+ACYH//6SBlwO/QkqBlwN3QnRDQkP//ytClwNtQnZDnoAPgKSBbUIXQ8EDdkNhgBlDCIBdgIBCCIAZQyaA//9hgBJD34C9QSSADoCUgPSAGoB+Q9RC//8QgNOAzIAsgQKAfkIEgKOAHIDCQaOABIDCQSyBLYACgASAG0MkQi2ACoD//wGAwkECgBVCDIBKgC+AIEJigA6BeoCjgC+AB4AtgBtDGUIAgN+AEYARgECAAIDfgAGAAIAGgKyAAYAygAOAAYAKgP//A4B/gXOARIDaQv//AoCKQkSA0kHcQUeAI4HaQgaAaoGvgBOAR4ATgN+AWUOBQgKAIEJKgEqATIAvgC6BDIBKgP//uEEHgAaBHYDMgASAL4AEgCBCBoD8gEhDD0MPQxCAfkJCQ7qAfkL//4CAD0MHQw9DvEJ+QrtBIoAtgI2BAoBmgAaAA4AxgASARoAHgACABIAxgAeA//8BgAGAAIAAgAeAxIAdgE5CzgMWgP//sQNOQrEDmQNngNFCsQOOQn5DyUIngFhCDkMGQ84DmQNOQrEDI4D//7EDTkKxA5kDO4HRQrEDjkJ+Q5CAPYBYQg5DTkPOA5kDRYDUQoNCY4EUgWOB1EL//2OBA4DKQXpCg0KDQiVCFIGLgAOADoAdgROAF4ALgAqA+EL//zZDqkKugFKBNkOcgWBCCoEYgJuAaIGSgY8D+EJGgLED0UJOQnhDC0KxAzJC//+1QbEDyUJ+Q05DBkNGgKuBa4DOA5kDw0LFA8UDtgNgQ7YDwwMhQp8D//+zQcUDwwO2A5wDhkOGQyFCxoCGQzCAmwP4Qf//fEOqgZsDUENLgANCmwPMQllDaoBOgLRBUkJ8QsQDfEOrgbED//+aQnhDI4CuA9yADkM8QpgDBkOZA5kDeEOogI5CMkLOA64Di4GbA2KBMIB8Q1JCmwPbQf//YoGbA8NCFUMxQhuAA0JIQk6AxAN8QxOASEPFQiVC4UEbgUhDgIC7QQyAIoDFQsVCxULFQiOBPIH//0hDxULEQtYDOEP//9YDV0PWA9YDekPDA9YDowPOA5YDwwNqgS1DwQPlA9YDN4D//6+ASoAEgG+Av0EvgC+ABIBxgdGAX4EMgAKAU4B0gC+ABIBHgP//34DNA84D1gOWA9YDwwPOA1xD1gPWA80D1gPOA5YDlgN6Q+UD1gPlA+cD4wPkA+cD4QPnA+cD4wPmA+cD///nA+YD5gPgA+MD5gPoA+cDgIBIQzOBwYDFQt2AB0PSQbqAI4FIQ///fkIzgG+BOIATgCOBmAMHQ///xQOCQ/BCxQO6QsUDtgPbgFRDxQOGQ7MDhkMHQ5yA6EJOQ+IDxQPkA+cD5wPnA+YD5wPnA+ED5gP//+cD5wPnA+cD5wPmA+YD4APoA+cDX4F+QzFCDYF+QzFCU0MVQ///4kF+QyZCVUNMgBGAX4EmQuNCtQNVQ///sQMLQmeAmQMLgLEDmQNYQg5DsQPRQnpDJkNTQ2eAq4GaQs4DmQPmA+gD///gA+cD4wPnA+cD5gPnA+cD5QPmA+YD5wPlA+YD5wPoA+cD5gPnA+cD5wPlA+UD5wPnA+cD5QPnA+cD5wPnA+cD5gPmA+YD///kAyyACYACgP//bYECgHdCdoBfgASAu0FIgAiBAIEIgS6AB4AsgBZDHELfA+UD5APfA+UD4gPlA+UD2APiA+UD4gPkA+ID///iA+ID5APnA+UD5gPnA+cD5wPlA+UD5wPnA+cD5QPnA+cD5wPnA+cD5gPmA+YD///kA1qAykJmgD+AeEKKgBlCD0L//4qAykIJgLVBCoAFgFqAroATgU5DeEIMgCiBAYAHgHyAEIABgHyAAoAZgOCADIBOgP//AYAMgCSAJIAogSCAc4A2QxiBIYGqQgaA8EICgd2AroD1Qv//7EHsQZyBE4BugB+AjwPwQttBxANZQ8xCFUMVQ5sDo0L1gF2B//8VQ1lDzEJLgFJCo0IxQsQDfEMdgAdCL4AcgKmBHYBEgc+AAYAcgKmBL4CHgP//AYAdgEGAV4DAQqmBB4B3QlKAVYB2gC6AH4EqgD2ALoC7Qf//CIEIgYOAB4ACgASABYAEgOYD6AP//+AD5wPjA+cD5wPmA+cD5wPlA+YD5gPnA+UD5gPnA+gD5wM/gHdCy0EIgUaACIF3Qv//g4AAgAuAwUHLQW2BCIF+gH6AE4B3QgiBRYDUQmuAQoCDQkWAJUIlQv//kIDMQgmAY4HagAKAEoBngB2BVUODQgCAo4ATgBOAK4AMgN2AB4AMgP//BIATgDyAPIAsgACADIABgCiBfID//35D40ImQuNCoIF+QxmBoEK5gFND40IVQxxDHEMNgROAHoC1A35D3wPlA+UD5AP//+QD5QPiA+QD2APlA+UD5QPlA+UD5APkA98D5QPfAwKAGUKVgF2AcoAfgBlCAoBDgAOADIBygL2AGIGQgAWA//8FgBlCGIERgIiB//8BgDOBEYCsgOeAAoBZgIiBAYB3gDCAMIADgB2AVoBLQiqBAoCVgVCAM4BQgCaAlYEPgCSAC4D//zyAbIBsgE2AG4ABgAGArkLrgP//sQMgQ+9CsQOqgbEDeEMnQ9FCsQMnQ3NDeENTQ4+AMULIQt4DsQOggX5DC4D//35D2EF+QxxDoIEcQ35DjoEcQ3VCHENfgTFCFUPVA35DLIB3QiyA//8cQgKAbYEIgQGAP4C7QQGArYAEgAGALoA/gH6Ad0LLQbRCqQN6Qm1CqQODQosDiwOJgQ5DqQP//44DQUMtgCxC7EJpQ90DpgNegBNDzUIqQhqBtUETQ///KkIFgNFBxULNQs1CeEKqgbmABIATQ81CAoAAgASAAYALgASA//8EgAKAAIATgAeAEYACgACAAIAEgAeAxIAcgLRCpgNkQ9RCekJAQyyAjgNBQ/RCqQMJQ44DQUNBQwdDaUM1Q8oD///lA+cD5wPmA+AD5gPmA+YD5gPkA+cD5wPnA+cD5wPmA+YD5QPnA///YkPgA2JD///WA5YD1gPOAwVDtQPWA7UDzgPgQX5DmQOZA8MD4APWA0WA1EJFgAKAg0K8gBtC1UEGgLaAg0K8gFmB//9CgEWAvIDygFVDg0JOgP//RkJGQgaAeIHuQkuA9UEvgFJCoUKhQqFCO0IvgXiAB4DmQgmBtIA8Q7NCs0IPgLNCNkMKgLNC//8dQjxDNkM8Q6pCs0LMQSiAPEPHQf///UK9QXmBHUKugP1CGIB5gXOAvkLHQWBCakIdQhGACoFugKID/UIagI6BqoCqgCuAaoBEgQKA0YABgJSA6YDhgEeBcYFMgP//AYCOgQKAuIA6Q85Bf4ELgLGAQEPOQX+BsYACQ85BuEJwQmZCEoAXgWGB//+4gK6APEMhgf//x0GcgTxDB4ERgAqAJUIbQrNCUoESgeyApoEKgTxDs0JLgJ1COIE4gVaB0YDuQkuAOIEGgFaBOIHrQUZC9UH//wuAB4DuQkZC4gPmA+UD5QP//+UD5gPhA+UD3QPmA+YD5gPmA+YD5QPlA+ED5gPdAyqBPEMAQ7NCD4AbQjZDGYCzQv//akI8QzZDPEOqQmpCpoFHgBiAeYEAgIiAEoANgBWAAIAAgACACYABgEyADYAcgDGAHIABgP//AYD9gA+ABIDuQjiBOIFGQgGA7kIRgfmAdIDuQvmA60FGQqWB//8LgL6A7kKhQjiAp0JYgAWAVYGdgORBB4AggCCAn4G9gJWB//8EgFiAnYA2gKdC70EhgFFCkICQgBCBWYBRQouAkIADgBCBi4BNgaOBFIEFgP//WYCrQvRBBIDEgACAA4BMgASAIoAvgAKAB4BmgP//HYABgACABIAJgBWAxIAvgCmAW0KQgEGASIEAgAWAloADgP///kGQgJOBoIBmgEGAkIBygFtCoIAEgMSAB4AEgAeACoD//xWAB4AHgGaAB4AAgAGAAIAHgAqACoCNgACAAYDdgCCAE4AfgAGAKIEHgBOA//8CgCCAUYA8gDyAAYAMgAGAH4F8gByAB0IBgP//0YAtgE2BAoABgBKACoEvgLiALYAvgB2AQYARgMBCTYE3gKtCD4H//xCB7oCrQjeAmoADgBaAN4EEQu6A9oCfgHmAN4CrQvRB///dgACADIAggAuA3YABgAGAAYBEgBOAAYAggAuAC4ABgAeAKIF8gLmAekOqgaqBT0M6gX5DHEOqgTFCfkN/QguA40LjQv//MYExQrUDT0OzgAxDBYD//wxDhoAfQm5ChoBegQxDCIAfQlSBGoGLgIuAoIF3Q8VCg4AIQ///BYAIQwGAs0JoQtWAGUIIQwyBGUIvgXeBiIBYgb5BCEMAQx2AB0IvgByATYEdgAqByID//0GAB0IBgLiAPoABgAOAHIBrgMBCqYHGA+ID1QPVA+ID1QPiA98D1QPbA+ID3wP//98D3wPUA9QD3APmA+ID";

            ExpectedDecompressedBytes    = Convert.FromBase64String(polyPhenBase64);
            NumExpectedUncompressedBytes = ExpectedDecompressedBytes.Length;
        }

        private static MemoryStream GetBlockStream(ICompressionAlgorithm compressionAlgorithm, byte[] bytes, int numBytes, out int copyLength)
        {
            var ms = new MemoryStream();
            var writeBlock = new Block(compressionAlgorithm);

            copyLength = writeBlock.CopyTo(bytes, 0, numBytes);
            writeBlock.Write(ms);
            writeBlock.WriteEof(ms);

            return ms;
        }

        [Fact]
        public void QuickLzBlock()
        {
            var ms = GetBlockStream(Zstd, ExpectedDecompressedBytes, NumExpectedUncompressedBytes, out var copyLength);
            ms.Seek(0, SeekOrigin.Begin);

            var readBlock = new Block(Zstd);
            readBlock.Read(ms);

            var observedDecompressedBytes = new byte[NumExpectedUncompressedBytes];
            var numObservedDecompressedBytes = readBlock.CopyFrom(observedDecompressedBytes, 0, copyLength);

            Assert.False(readBlock.IsFull);
            Assert.False(readBlock.HasMoreData);
            Assert.Equal(NumExpectedUncompressedBytes, numObservedDecompressedBytes);
            Assert.Equal(ExpectedDecompressedBytes, observedDecompressedBytes);
        }

        [Fact]
        public void BlockZeroLengthCopy()
        {
            var writeBlock = new Block(Zstd);
            const int expectedCopyLength = 0;

            Assert.Equal(expectedCopyLength, writeBlock.CopyTo(ExpectedDecompressedBytes, 0, 0));
            Assert.Equal(expectedCopyLength, writeBlock.CopyFrom(ExpectedDecompressedBytes, 0, 0));
        }

        [Fact]
        public void BlockWrongSize()
        {
            var ms = GetBlockStream(Zstd, ExpectedDecompressedBytes, NumExpectedUncompressedBytes, out _);
            ms.Seek(0, SeekOrigin.Begin);

            var readBlock = new Block(Zstd);

            using (var updatedMs = new MemoryStream())
            {
                updatedMs.Write(ms.ToArray(), 0, (int)ms.Length);
                updatedMs.Seek(0, SeekOrigin.Begin);

                // read the original header
                var header = new BlockHeader();
                header.Read(updatedMs);

                // change and write the header
                header.NumUncompressedBytes--;
                updatedMs.Seek(0, SeekOrigin.Begin);
                header.Write(updatedMs);

                // read the updated block
                updatedMs.Seek(0, SeekOrigin.Begin);
                // ReSharper disable once AccessToDisposedClosure
                Assert.Throws<CompressionException>(delegate { readBlock.Read(updatedMs); });
            }
        }

        [Fact]
        public void BlockTruncation()
        {
            var ms = GetBlockStream(Zstd, ExpectedDecompressedBytes, NumExpectedUncompressedBytes, out _);
            ms.Seek(0, SeekOrigin.Begin);

            var readBlock = new Block(Zstd);

            using (var truncatedMs = new MemoryStream())
            {
                truncatedMs.Write(ms.ToArray(), 0, (int)ms.Length - 100);
                truncatedMs.Seek(0, SeekOrigin.Begin);
                // ReSharper disable once AccessToDisposedClosure
                Assert.Throws<IOException>(delegate { readBlock.Read(truncatedMs); });
            }
        }

        [Fact]
        public void UncompressedBlockTruncation()
        {
            const int bufferSize = 10000;
            var buffer = BlockStreamTests.GetRandomBytes(bufferSize);

            var ms = GetBlockStream(Zstd, buffer, bufferSize, out _);
            ms.Seek(0, SeekOrigin.Begin);

            var readBlock = new Block(Zstd);

            using (var truncatedMs = new MemoryStream())
            {
                truncatedMs.Write(ms.ToArray(), 0, (int)ms.Length - 100);
                truncatedMs.Seek(0, SeekOrigin.Begin);
                // ReSharper disable once AccessToDisposedClosure
                Assert.Throws<IOException>(delegate { readBlock.Read(truncatedMs); });
            }
        }
    }
}
