language: c
compiler:
  - gcc
  - clang
env:
  - BUILDDIR=. TOOL="./configure"
  - BUILDDIR=../build TOOL="../zlib-ng/configure"
  - BUILDDIR=. TOOL="cmake ."
  - BUILDDIR=../build TOOL="cmake ../zlib-ng"
script: mkdir -p $BUILDDIR && cd $BUILDDIR &&
        $TOOL && make && make test
